#!/bin/csh -f

# script to include a priori mascon values in graceorb
#
# P. Tregoning
# 1 June 2019

if ($#argv == 0)then
  echo "sh_apriori_msc GRACE_FO.input IC_file.vcv mascon_file.vcv"
  exit
endif

set input_file = $1
set IC_file = $2
set mascon_file = $3

# chnange the GRACE input file to turn on mascons and use them a priori
cat $input_file | sed s/"MASCON            : N"/"MASCON            : Y"/ | sed s/"USE_APRIORI_MCS   : N"/"USE_APRIORI_MCS   : Y"/ > GRACE.input.tmp ; mv -f GRACE.input.tmp $input_file

# change the number of parameters in the input vcv file
set nmsc = `grep " MC" $mascon_file | wc -l | awk '{printf "%5.5d\n", $1}'`
set ntot = `echo $nmsc | awk '{printf "%5.5d\n", $1 + 24}'`
echo mascon file has $nmsc mascons
head -41 $IC_file | sed s/"Number of estimated parameters:      24      0      0"/"Number of estimated parameters:   "$ntot"  "$nmsc"      0"/ > IC_tmp.vcv
grep " MC" $mascon_file >> IC_tmp.vcv
mv -f IC_tmp.vcv $IC_file

