#!/bin/csh -f

# script to run a cron job to update the finals.unso.data table every week
#
# P. Tregoning
# 13 February 2022

# change to the tables directory
cd /Mdata/GRACE/software/tables

# run the script
/Mdata/GRACE/software/active/com/sh_update_usno.finals Y

ls -lt | head
