#!/bin/csh -f

# script to update the L1B data. Because it appears at random times, perhaps just run this every day?

cd /home/geod/pault/temp_L1B


# run the script
# PT230203: the year is hardwired into this for now ...
/Mdata/GRACE/software/active/com/sh_update_weekly_L1B 2023 RL04


