#!/bin/csh -f

# script to plot the differences between one input VCV file and two others
#
# P. Tregoning
# 6 December 2022

if ($#argv == 0)then
  echo "sh_diff_solns -soln1 soln1.vcv -soln2 soln2.vcv -soln3 soln3.vcv -mascon_file mascons_stage5_V006_200km -y ymin ymax y_int -y_polar ymin ymax y_int  -plot_only Y/N "
  exit
endif

#############################
#  defaults
set version = ~/ga
set mascon_file = $version/tables/mascons_stage5_V006_200km
set plot_only = N
set n_decimate = 10

set ymin = -600 
set ymax = 600
set y_int = 10

set polar_min = -5000
set polar_max = 1000
set polar_int = 100

#############################


##################### DECIPHER COMMAND LINE #######################
while ($#argv > 0 )
  set input = ( $argv )
  switch($input[1])
    case -soln1:
      set soln1  = $input[2]
    breaksw
    case -soln2:
      set soln2  = $input[2]
    breaksw
    case -soln3:
      set soln3  = $input[2]
    breaksw
    case -soln4:
      set soln4  = $input[2]
    breaksw
    case -y:
      set ymin = $input[2] ; shift argv  
      set ymax = $input[3] ; shift argv
      set y_int = $input[4] ; shift argv
    breaksw
    case -y_polar:
      set polar_min = $input[2] ; shift argv  
      set polar_max = $input[3] ; shift argv
      set polar_int = $input[4] ; shift argv
    breaksw
    case -yanot:
      set yanot = $input[2]
    breaksw
    case -x:
      set xmin = $input[2] ; shift argv  
      set xmax = $input[3] ; shift argv
    breaksw
    case -plot_only:
      set plot_only = $input[2]
    breaksw
    case -n_decimate:
      set n_decimate = $input[2]
    breaksw
 endsw
  if ( $#argv > 0 ) shift argv
end
alldone:
######################################################################


if ($plot_only != "Y")then
  # difference soln2 from soln1
  echo " "
  echo "****Difference between " $soln1 and $soln2
  ${version}/util/diff_ternarys $mascon_file  $soln1 $mascon_file  $soln2 diff_${soln1}-${soln2}.dat N N $n_decimate 1.0

  # difference soln3 from soln1
  echo " "
  echo "****Difference between " $soln1 and $soln3
  ${version}/util/diff_ternarys $mascon_file  $soln1 $mascon_file  $soln3 diff_${soln1}-${soln3}.dat N N $n_decimate 1.0
  
  # difference soln4 from soln1
  echo " "
  echo "****Difference between " $soln1 and $soln4
  ${version}/util/diff_ternarys $mascon_file  $soln1 $mascon_file  $soln4 diff_${soln1}-${soln4}.dat N N $n_decimate 1.0

endif


plot:
set outfile = plot_diffs.ps

gmt gmtset PS_MEDIA ledger
gmt gmtset FONT_TITLE 15p,Helvetica,black
gmt makecpt -Cgrace -T$ymin/$ymax/$y_int > ewh.cpt
gmt makecpt -Cgrace_lopsided5 -T$polar_min/$polar_max/$polar_int > ewh_polar.cpt

set proj = "-JR30/13"
set proj_ant = "-JS0/-89.9/30/6.5"
set proj_arctic = "-JS0/89.9/45/6.5"

set range = "-Rg"
set range_ant = "-R0/360/-90/-60"
set range_arctic = "-R0/360/55/90"


# plot the apriori for this iteration
echo Plotting $soln1 - $soln2
gmt psxy diff_${soln1}-${soln2}.dat $proj $range -: -Sc0.2 -Cewh.cpt -X0.3 -Y17 -P -K > $outfile
gmt pscoast $proj $range -Ba1000:."${soln1}-${soln2}":nesw -Dc -Wthin,100/100/100 -O -K >> $outfile
gmt psscale -Cewh.cpt -D6.5/-1/12/0.3h -Ba300f150:"EWH (mm)": -O -K >> $outfile

gmt psxy diff_${soln1}-${soln2}.dat $proj_ant $range_ant -: -Sc0.2 -Cewh.cpt -Y-10 -O -K >> $outfile
gmt pscoast $proj_ant $range_ant -Ba1000nesw -Dc -Wthin,100/100/100 -O -K >> $outfile
gmt psscale -Cewh_polar.cpt -D6.5/-1/12/0.3h -Ba2000f1000:"EWH (mm)": -O -K >> $outfile


gmt psxy diff_${soln1}-${soln2}.dat $proj_arctic $range_arctic -: -Sc0.2 -Cewh.cpt -X+7 -O -K >> $outfile
gmt pscoast $proj_arctic $range_arctic -Ba1000nesw -Dc -Wthin,100/100/100 -O -K >> $outfile


#######################################
# plot soln1 - soln3
echo Plotting $soln1 - $soln3
gmt psxy diff_${soln1}-${soln3}.dat $proj $range -: -Sc0.2 -Cewh.cpt -X+7.5 -Y+10 -O -K  >> $outfile
gmt pscoast $proj $range -Ba1000:."${soln1}-${soln3}":nesw -Dc -Wthin,100/100/100 -O -K >> $outfile
gmt psscale -Cewh.cpt -D6.5/-1/12/0.3h -Ba300f150:"EWH (mm)": -O -K >> $outfile

gmt psxy diff_${soln1}-${soln3}.dat $proj_ant $range_ant -: -Sc0.2 -Cewh.cpt -Y-10 -O -K >> $outfile
gmt pscoast $proj_ant $range_ant -Ba1000nesw -Dc -Wthin,100/100/100 -O -K >> $outfile
gmt psscale -Cewh_polar.cpt -D6.5/-1/12/0.3h -Ba2000f1000:"EWH (mm)": -O -K >> $outfile


gmt psxy diff_${soln1}-${soln3}.dat $proj_arctic $range_arctic -: -Sc0.2 -Cewh.cpt -X+7 -O -K >> $outfile
gmt pscoast $proj_arctic $range_arctic -Ba1000nesw -Dc -Wthin,100/100/100 -O -K >> $outfile


#######################################
# plot soln1 - soln4
echo Plotting   $soln1 - $soln4
gmt psxy diff_${soln1}-${soln4}.dat $proj $range -: -Sc0.2 -Cewh.cpt -X+7.5 -Y+10 -O -K  >> $outfile
gmt pscoast $proj $range -Ba1000:."${soln1}-${soln4}":nesw -Dc -Wthin,100/100/100 -O -K >> $outfile
gmt psscale -Cewh.cpt -D6.5/-1/12/0.3h -Ba300f150:"EWH (mm)": -O -K >> $outfile

gmt psxy diff_${soln1}-${soln4}.dat $proj_ant $range_ant -: -Sc0.2 -Cewh.cpt -Y-10 -O -K >> $outfile
gmt pscoast $proj_ant $range_ant -Ba1000nesw -Dc -Wthin,100/100/100 -O -K >> $outfile
gmt psscale -Cewh_polar.cpt -D6.5/-1/12/0.3h -Ba2000f1000:"EWH (mm)": -O -K >> $outfile

gmt psxy diff_${soln1}-${soln4}.dat $proj_arctic $range_arctic -: -Sc0.2 -Cewh.cpt -X+7 -O -K >> $outfile
gmt pscoast $proj_arctic $range_arctic -Ba1000nesw -Dc -Wthin,100/100/100 -O  >> $outfile


gs $outfile

  


