#!/bin/csh -f

# script to calculate day-of-year and graceseconds for a given yyyy-mm-dd
#
# P. Tregoning
# 28 January 2022

if($#argv == 0)then
  echo sh_doy YYYY MM DD
  exit
endif

set version = ~/ga

# graceseconds
set graceseconds = `$version/com/sh_graceseconds $1 $2 $3`

# how many days in this particular year?
set ndays = `date -d${1}-12-31 +%j`

# get the day of year
set doy = `date -d${1}-${2}-${3} +%j`

# decimal year
set dec_yr = `echo $1 $doy $ndays | awk '{printf "%10.5f\n", $1 + $2 / $3}'`

# output
echo $graceseconds
echo "Day of Year :" $doy
echo "Decimal Year:" $dec_yr

