#!/bin/csh -f

# script to extract and print to the screen the GTORB header information

set version = ~/gt

if ($#argv == 0 ) then
  echo "sh_GTORB_header GTORB_file [number of header lines]"
  exit
endif

set gtorbfile = $1
if($#argv == 2)then
  set n_hdr_lines = $2
else
  set n_hdr_lines = 26
endif

set i = 1
while ($i <= $n_hdr_lines)
  $version/util/read_GTORB_record $gtorbfile $i C | awk '{if ($5 == "(TERRESTRIAL)") {print $0} else {print substr($0,1,190) } }'
  @ i = $i + 1
end


