#!/bin/csh -f

# script to calculate the altitude of the GRACE satellites, given a GNV1B file
#
# P. Tregoning
# 2 September 2020

if ($#argv == 0)then
  echo sh_GRACE_altitude GNV1B_2016-06-10_A_02.asc
  exit
endif

set GNV1B_file = $1
set mascon_file = ~/gg/grace/tables/mascons_stage5_V004


set gracesec = `grep " E " $GNV1B_file | awk '{print $1}'`
set sat_X = `grep " E " $GNV1B_file | awk '{print $4}'`
set sat_Y = `grep " E " $GNV1B_file | awk '{print $5}'`
set sat_Z = `grep " E " $GNV1B_file | awk '{print $6}'`
set n_epochs = 9000   #`echo $sat_X | wc -w`


# loop through all the epochs
set iepoch = 1
while ($iepoch <= $n_epochs)
  # convert to spherical lat/lon
  set latlonrad = `~/bin/xyz_to_latlon $sat_X[$iepoch] $sat_Y[$iepoch] $sat_Z[$iepoch] | tail -1 | awk '{print $4, $5, $6}'`

  # find the primary mascon over which the satellite is located
  set msc_prim = `~/gt/com/sh_which_mascon $latlonrad[1] $latlonrad[2] $mascon_file | tail -1 | awk '{print $5}'`

  # get the radius of this primary mascon
  set msc_rad = `grep " "$msc_prim"  P" $mascon_file | awk '{if ($11 < 1020) {print $7 + $9 + $10 } else {print $7 + $10}}'`

  # difference the two radii to get the altitude of the satellite
  echo $latlonrad $msc_rad  $iepoch | awk '{printf "%10.4f %10.4f %15.4f %10d\n",$1, $2, $3 - $4, $5}'

  @ iepoch = $iepoch + 1

end

exit



