#!/bin/bash

mkdir -p gt_version

for F in `ls sh_*`
do
    Y=`grep 'set version = "~/gt"' ${F}`
    if [ "$Y" ]
    then
	echo $F
	FO="gt_version/${F}_gt"
	mv ${F} ${FO}
	cat ${FO} |sed s:'set version = "~/gt"':'set version = "~/ga"':>${F}
	chmod 775 ${F}
    fi
       
done


for F in `ls sh_*`
do
    Y=`grep 'set version = ~/gt' ${F}`
    if [ "$Y" ]
    then
	echo $F
	FO="gt_version/${F}_gt"
	mv ${F} ${FO}
	cat ${FO} |sed s:'set version = ~/gt':'set version = ~/ga':>${F}
	chmod 775 ${F}
    fi

done  
	
