#!/bin/csh -f

# script to install and compile the ANU GRACE Analysis software
#
# P. Tregoning
# 16 March 2017


# .... loads of things to go in the start of this, related to unpacking tarfiles etc ...



set version = ~/gg//grace/active



#########################################
#         make the BLAS library         #
#########################################
cd $version/BLAS
make

#########################################
#         make the module files         #
#########################################
cd $version/mod_subs
sh_make


#########################################
#         make the grace library        #
#########################################
cd $version/lib
make

#########################################
#          make the util library        #
#########################################
cd $version/util
make

#########################################
#             GRACEORB                  #
#########################################
cd $version/graceorb
make

#########################################
#              GRACEFIT                 #
#########################################
cd $version/gracefit
make


#########################################
#              GRACEKAL                 #
#########################################
cd $version/gracekal
make



#########################################
# set up the links in the bin directory #
#########################################
cd $version
sh_bin_links


