#!/bin/csh -f

# script to turn a mascon solution into spherical harmonics ....
#
# PT200922: -vcv now indicates that a vcv solution file is to be read. "-soln" is the way to enter the input solution file.

if ($#argv == 0)then
  echo "sh_msc_to_sph -soln addnorm.vcv [-vcv  -out msc.sph -version ~/gt -grid_int 0.5 -mascon_file mascons_stage4 -start_lat 90. -start_lon 0 ]"
  exit
endif

##################### DEFAULTS #######################
set version = "~/gt"
set mascon_file = ~/gg/grace/tables/mascons_stage4
set grid_int = 0.5
set start_lat = 90.
set start_lon = 0.
set vcv = " "

set output_file = msc.sph
##################### DECIPHER COMMAND LINE #######################
while ($#argv > 0 )
  set input = ( $argv )
  switch($input[1])
    case -soln:
      set soln_file = $input[2] ; shift argv  
    breaksw
    case -vcv:
      set vcv = "vcv"  
    breaksw
    case -msc:
    case -mascon_file:
      set mascon_file = $input[2] ; shift argv  
    breaksw
    case -o*:
      set output_file = $input[2] ; shift argv  
    breaksw
    case -grid:
      set grid_int = $input[2] ; shift argv  
    breaksw
    case -version:
      set version = $input[2] ; shift argv  
    breaksw
    case -start_lat:
      set start_lat = $input[2] ; shift argv  
    breaksw
    case -start_lon:
      set start_lon = $input[2] ; shift argv  
    breaksw
 endsw
  if ( $#argv > 0 ) shift argv
end
alldone:
######################################################################

# convert from mascons to a regular grid
echo ${version}/util/msc_to_grid $mascon_file $soln_file TAPE1 $grid_int $start_lat $start_lon $vcv
${version}/util/msc_to_grid $mascon_file $soln_file TAPE1 $grid_int $start_lat $start_lon $vcv


## reformat for analyse_hs
#REFORMAT_MOY 361 721 0.5 junk > TAPE1

# set up the command file for analyse_hs
echo "0                                                      # 0:degre 1:minute "  > TAPE3                                  
echo "0.50 0.50                                     # pas en latitude et longitude" >> TAPE3                        
echo "1                                             # 1 --> grille sur sphere, 2 --> grille sur ellipsoide" >> TAPE3
echo "0                                             # longitude du coin sup. gauche de la grille           " >> TAPE3
echo "1                                             # 0 : BINAIRE - 1 : FORMATTE                           " >> TAPE3
echo "180                                           # degre max. pour calcul des harmoniques               " >> TAPE3
echo "0                                             #                                                      " >> TAPE3
echo "1.0                                           # facteur d'echelle                                    " >> TAPE3
echo "0                                             #                                                      " >> TAPE3
echo "1                                             # pour sorties 0:non  1:oui                            " >> TAPE3
echo "analyse_Tregoning                             # commentaire ecrit dans le fichier de sortie          " >> TAPE3
echo "0                                             # 0 ---> ON EST EN METRE 1 ---> ON EST EN KM           " >> TAPE3
echo "6378140. 0.0 3.98847914E14 7.272205E-5         # a, uapl, GM, vitesse de rotation terrestre (rad/s)  " >> TAPE3
echo "" >> TAPE3

# run analyse_hs
analyse_hs < TAPE3
cat TAPE2 | sort -gk 1,1 -gk 2,2 > ${output_file}

ls -l ${output_file}
grep "  2    0 " ${output_file}
exit




set outfile = junk.ps
makecpt -Chaxby -T-.805/.805/.010 > junk.cpt

pscoast -JR30/15 -Rg -Ba1000nesw -X2 -Y10 -P -K -W1 > $outfile
psxy    -JR30/15 -Rg junk -: -Sc0.1 -Cjunk.cpt -O -K >> $outfile
pscoast -JR30/15 -Rg -Ba1000nesw -O -K -W1 -A10000 >> $outfile


gs $outfile

