#!/bin/csh -x

# PT190314 : generate a mascon file with the following:
#
# Oceans		: 300x300 km (takes a long time. Use a file already done)
# Arctic/Southern Ocean : 200x200 km
# Antarctic             : 100x100 km 
# Pine Is, Thwaites     : 100x100 km
# Greenland             : 100x100 km
# Murray-Darling Basin  : 200x200 km
# Lake Eyre             : kept as single, small mascon
# Amazon                : 200x200 km
# Caspian Sea           : 200x200 km
#
# all other continents  : 200x200 km
#
# NOTE: overlapping Centres of Mass of ocean/land mascons are fixed, and primary mascons with too few ternarys
#       are merged with neighbouring primarys

set land_area = 4.e10
set polar_area = 1.e10
set ocean_area = 9.e10
set ext = $3
set version = "~/gt"
set maxOMP = 10

set script = "Y"

# link the required files into the directory
ln -s -f  ~/gg/grace/tables/GEBCO14+Bedmap2_topo.nc .
ln -s -f  ~/gg/grace/tables/Und_min2.5x2.5_egm2008_isw=82_WGS84_TideFree_SE
ln -s -f  ~/gg/grace/tables/mascon.polygons .
 

# PT190409: apparently each region needs a different RMS cutoff once we put a cap on the max number
#           of ternarys per primary. Set the RMS cutoffs here for each region
#
# Region order is:
# cutoff[1] = Eurasia     = 6000.
# cutoff[2] = Caspian     =  6000.   It goes into an infinite loop
# cutoff[3] = Arctic      =  100.    Takes 30 mins to reduce RMS down to zero
# cutoff[4] = SthnO       =  6000.   takes 30 mins to reach RMS of 5800. Don't know whether it reaches < 1000 ....
# cutoff[5] = Amazon      =  2300.
# cutoff[6] = MurrayDB    =  2000.
# cutoff[7] = Australasia =  8000.
# cutoff[8] = SAmerica    =  8000.
# cutoff[9] = NAmerica    = 12000.
# cutoff[10] = Africa     =  3000.
# cutoff[11] = Pine_Is    = 10000.
# cutoff[12] = Thwaites   =  8000.
# cutoff[13] = Japan      =  4600.
# cutoff[14] = Asian_Isla = 13000.
# cutoff[15] = Antarctica = 
# cutoff[16] = Greenland  = 

set cutoff = ( 6000. 6000. 100. 100. 2300. 2000. 8000. 8000. 12000. 3000. 10000. 8000. 4600. 13000. 100. 1000.)
#goto CoM100
#goto CPU1
goto skip_ocean

################################################################################################
# first, initialise the mascons
echo ${version}/util/init_mascons
${version}/util/init_mascons

# now, assign attributes to them (density, depth etc) and form 3x3 deg primary mascons
echo ${version}/util/classify_mascons
${version}/util/classify_mascons


# separate the continental from the ocean mascons. Assign a continental shelf depth of -0.1 m to remove it
${version}/util/separate_mascons mascons_stage2 mascons_stage3_0.1m -0.1
################################################################################################


#################################################################################################
# the oceans. Need to run the reshape of the oceans on compute2 in order to have enough memory. #
#################################################################################################
# reshape the arctic down to 3 deg tiles
# Arctic	: breaks 143 into 178 mascons in 193 iterations (15 mins)
setenv OMP_NUM_THREADS 5
${version}/util/reshape_mascons mascons_stage3_0.1m mascons_stage4_Arctic Arctic 9.e10 100.
set nterns = `cat mascons_stage4_Arctic | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l`
if($nterns  != 1485118)then
  echo We have lost some ternarys. There are only $nterns left ...
  if($script == "Y")exit
endif

# reshape the southern ocean down to 3 deg tiles
# Southern Ocean: breaks 172 into 208 mascons in XX iterations
${version}/util/reshape_mascons mascons_stage4_Arctic mascons_stage4_SthnO SthnO  9.e10  100.
set nterns = `cat mascons_stage4_SthnO | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l`
if($nterns  != 1485118)then
  echo We have lost some ternarys. There are only $nterns left ...
    if($script == "Y")exit
endif

# now the rest of the ocean. This one takes several hours ....
# Ocean		: breaks XX into XX mascons in XX iterations
setenv OMP_NUM_THREADS 8
${version}/util/reshape_mascons mascons_stage4_SthnO  mascons_stage4_ocean Ocean 9.e10   1000. 2 Arcti SthnO     
set nterns = `cat mascons_stage4_ocean | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l`
if($nterns  != 1485118)then
  echo We have lost some ternarys. There are only $nterns left ...
  if($script == "Y")exit
endif

# stop after doing the oceans and then transfer the rest to compute1
exit
################################################################################################






skip_ocean:
#################################################################################################
# PT190321: start with Eurasia, since it takes the longest after the oceans
#################################################################################################
cp mascons_stage4_ocean mascons_stage4_tmp
setenv OMP_NUM_THREADS 10
set n_cutoff = 1
# Eurasia       : breaks 465 into 1272 mascons in 108 iterations
foreach region (Eurasia)
  ${version}/util/reshape_mascons mascons_stage4_tmp mascons_stage4_${region} $region $land_area $cutoff[$n_cutoff]  1 Casp 
  ${version}/util/lost_ternarys mascons_stage4_${region}
  if(`cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
    echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
    if($script == "Y")exit
  else
    cp mascons_stage4_${region} mascons_stage4_tmp
    @ n_cutoff = $n_cutoff + 1
  endif
end
#################################################################################################



###################################################################
##                                                               ##
## PT190308: reshape the Caspian Sea into smaller mascons        ##
##                                                               ##
###################################################################
# Caspian  : makes  18 mascons.   9 iterations.
setenv OMP_NUM_THREADS 1
set n_cutoff = 2
cp mascons_stage4_Eurasia mascons_stage4_tmp
set Casp_mascon = `grep "  P" mascons_stage4_tmp | grep PCasp | awk '{print $1}'`
${version}/util/reshape_mascons mascons_stage4_tmp mascons_stage4_Caspian MC$Casp_mascon $land_area $cutoff[$n_cutoff]
${version}/util/lost_ternarys mascons_stage4_Caspian
if(`cat mascons_stage4_Caspian | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
  echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_Caspian | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
  if($script == "Y")exit
else
  cp mascons_stage4_Caspian mascons_stage4_tmp
  @ n_cutoff = $n_cutoff + 1
endif



#################################################################################################
# PT190314: redo the Southern Ocean and the Arctic to reduce from 300x300 km to 200x200 km
#################################################################################################
# Arctic : breaks  176 mascons into  398 mascons.  198 Iterations
# SthnO  : breaks  250 mascons into  564 mascons.   53 iterations.
setenv OMP_NUM_THREADS 10
set n_cutoff = 3
foreach region (Arctic SthnO)
  ${version}/util/reshape_mascons mascons_stage4_tmp mascons_stage4_${region} $region $land_area $cutoff[$n_cutoff]   
  ${version}/util/lost_ternarys mascons_stage4_${region}
  if(`cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
    echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
    if($script == "Y")exit
  else
    cp mascons_stage4_${region} mascons_stage4_tmp
    @ n_cutoff = $n_cutoff + 1
  endif
end
#################################################################################################


###################################################################
##                                                               ##
## PT190308: extract out particular drainage basins              ##
##                                                               ##
###################################################################
# Amazon    : makes 169 mascons.   53 iterations.
# MurrayDB  : makes  27 mascons.   16 iterations.
setenv OMP_NUM_THREADS 10
set n_cutoff = 5
cp mascons_stage4_SthnO mascons_stage4_tmp
foreach region (Amazon MurrayDB)
  ${version}/util/grab_mascons mascons_stage4_tmp mascons_stage4_tmp2 mascon.polygons $region Land 100.
  set last_mascon = `grep "  P" mascons_stage4_tmp2 | tail -1 | awk '{print $1}'`
  ${version}/util/reshape_mascons mascons_stage4_tmp2 mascons_stage4_$region MC$last_mascon $land_area $cutoff[$n_cutoff]
  ${version}/util/lost_ternarys mascons_stage4_$region
  if(`cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
    echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
    if($script == "Y")exit
  else
    cp mascons_stage4_${region} mascons_stage4_tmp
    @ n_cutoff = $n_cutoff + 1
  endif
end

# now do the surrounding regions of SAmerica and Australasia
# Australasia	: breaks  70 into 175 mascons in  25 iterations. 7500 cutoff for Aus
# SAmerica      : breaks 123 into 278 mascons in  15 iterations
setenv OMP_NUM_THREADS 10
set n_cutoff = 7
foreach region (Australasia SAmerica)
  ${version}/util/reshape_mascons mascons_stage4_tmp mascons_stage4_${region} $region $land_area $cutoff[$n_cutoff] 3 Eyre Murra Amazo
  ${version}/util/lost_ternarys mascons_stage4_$region
  if(`cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
    echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
    if($script == "Y")exit
  else
    cp mascons_stage4_${region} mascons_stage4_tmp
    @ n_cutoff = $n_cutoff + 1
  endif
end

#################################################################################################
# PT190314: now do NAmerica and Africa
#
#   two of the Great Lakes contain ternarys with salt water densities .... issue not yet resolved
#################################################################################################
# NAmerica : breaks  203 mascons into  548 mascons.   34 Iterations
# Africa   : breaks  272 mascons into  751 mascons.  171 iterations.
setenv OMP_NUM_THREADS 10
set n_cutoff = 9
foreach region (NAmerica Africa)
  ${version}/util/reshape_mascons mascons_stage4_tmp mascons_stage4_${region} $region $land_area $cutoff[$n_cutoff] 
  ${version}/util/lost_ternarys mascons_stage4_$region
  if(`cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
    echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
    if($script == "Y")exit
  else
    cp mascons_stage4_${region} mascons_stage4_tmp
    @ n_cutoff = $n_cutoff + 1
  endif
end

# now clean up ?
~/gt/com/sh_cleanup_mascon_file -f mascons_stage4_Africa -out mascons_stage4_continents_cleaned -min_tern 41 -only_small Y
mv mascons_stage4_tmp mascons_stage4_continents_cleaned



###################################################################
##                                                               ##
## PT190308: extract out particular Antarctic drainage basins    ##
##                                                               ##
###################################################################
# Pine_Is   : makes   8 mascons.    9 iterations.
# Thwaites  : makes  19 mascons.   17 iterations.
setenv OMP_NUM_THREADS 1
set n_cutoff = 11
cp mascons_stage4_continents_cleaned mascons_stage4_tmp
foreach region (Pine_Is  )
  ${version}/util/grab_mascons mascons_stage4_tmp mascons_stage4_tmp2 mascon.polygons $region Land 100.
  set last_mascon = `grep "  PPine" mascons_stage4_tmp2 | tail -1 | awk '{print $1}'`
  ${version}/util/reshape_mascons mascons_stage4_tmp2 mascons_stage4_$region MC$last_mascon $polar_area $cutoff[$n_cutoff]
  ${version}/util/lost_ternarys mascons_stage4_$region
  if(`cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
    echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
    if($script == "Y")exit
  else
    cp mascons_stage4_${region} mascons_stage4_tmp
    @ n_cutoff = $n_cutoff + 1
  endif
end

set n_cutoff = 12
cp mascons_stage4_Pine_Is mascons_stage4_tmp
foreach region ( Thwaites )
  ${version}/util/grab_mascons mascons_stage4_tmp mascons_stage4_tmp2 mascon.polygons $region Land 100.
  set last_mascon = `grep "  P" mascons_stage4_tmp2 | grep -v "  Pine_I" | tail -1 | awk '{print $1}'`
  ${version}/util/reshape_mascons mascons_stage4_tmp2 mascons_stage4_$region MC$last_mascon $polar_area $cutoff[$n_cutoff]
  ${version}/util/lost_ternarys mascons_stage4_$region
  if(`cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
    echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
    if($script == "Y")exit
  else
    cp mascons_stage4_${region} mascons_stage4_tmp
    @ n_cutoff = $n_cutoff + 1
  endif
end



CPU1:
# now the regions with 1 CPU. These all run really quickly.
setenv OMP_NUM_THREADS 1
set n_cutoff = 13
foreach region (Japan Asian_isla)
  ${version}/util/reshape_mascons mascons_stage4_tmp mascons_stage4_${region} $region $land_area $cutoff[$n_cutoff]
  ${version}/util/lost_ternarys mascons_stage4_$region
  if(`cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
    echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
    if($script == "Y")exit
  else
    cp mascons_stage4_${region} mascons_stage4_tmp
    @ n_cutoff = $n_cutoff + 1
  endif
end


# cleanup, including CoM comparisons
~/gt/com/sh_cleanup_mascon_file -f mascons_stage4_Asian_isla -out mascons_stage4_continents_cleaned2 -min_tern 20 -only_small N
mv mascons_stage4_tmp mascons_stage4_continents_cleaned2

###################################################################
##                                                               ##
# Antarctica and Greenland
##                                                               ##
###################################################################
# Antarctica	: breaks 106 into 1186 mascons in  41 iterations
# Greenland     : breaks  20 into  222 mascons in  32 iterations
setenv OMP_NUM_THREADS 10
set n_cutoff = 15
foreach region (Antarctica Greenland)
  ${version}/util/reshape_mascons mascons_stage4_tmp mascons_stage4_${region} $region $polar_area $cutoff[$n_cutoff] 2 PineIs Thwaites
  ${version}/util/lost_ternarys mascons_stage4_$region
  if(`cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
    echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
    if($script == "Y")exit
  else
    cp mascons_stage4_${region} mascons_stage4_tmp
    @ n_cutoff = $n_cutoff + 1
  endif
end

# Pine Island hasn't been done, but it should have been. Do it again now to complete the file
setenv OMP_NUM_THREADS 1
set n_cutoff = 11
set region = Pine_Is
${version}/util/reshape_mascons mascons_stage4_tmp mascons_stage4_$region $region $polar_area $cutoff[$n_cutoff]
${version}/util/lost_ternarys mascons_stage4_$region
if(`cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
  echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
  if($script == "Y")exit
else
  cp mascons_stage4_${region} mascons_stage4_tmp
endif

mv mascons_stage4_tmp mascons_stage4_RMS100
${version}/com/sh_cleanup_mascon_file -f mascons_stage4_RMS100

echo We should be done with reshaping down to Land $land_area and Polar $polar_area
exit

































# rename the final file
mv mascons_stage4_tmp mascons_stage4_190314_reshaped

# finally, fix the small mascons and the CoM issues. The output file of the script is still called msc_file_tmp
# started at 9:39. Completed at ?????
/home/geod/pault/gt/com/sh_cleanup_mascon_file -f mascons_stage4_190314
cp msc_file_tmp mascons_stage4_190314_cleaned

###################################################################
##                                                               ##
## PT190308: extract out particular drainage basins              ##
##                                                               ##
###################################################################
setenv OMP_NUM_THREADS 1
cp mascons_stage4_190308_cleaned mascons_stage4_tmp
foreach region (Amazon MurrayDB)
  ${version}/util/grab_mascons mascons_stage4_tmp mascons_stage4_tmp2 drainage_basins $region Land 100.
  set last_mascon = `grep "  P" mascons_stage4_tmp2 | tail -1 | awk '{print $1}'`
  ${version}/util/reshape_mascons mascons_stage4_tmp2 mascons_stage4_$region MC$last_mascon 9.e10 100.
  ${version}/util/lost_ternarys mascons_stage4_$region
  if(`cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
    echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
    exit
  else
    cp mascons_stage4_${region} mascons_stage4_tmp
  endif
end

###################################################################
##                                                               ##
## PT190308: reshape the Caspian Sea into smaller mascons        ##
##                                                               ##
###################################################################
setenv OMP_NUM_THREADS 1
set Casp_mascon = `grep "  P" mascons_stage4_MurrayDB | grep PCasp | awk '{print $1}'`
${version}/util/reshape_mascons mascons_stage4_MurrayDB mascons_stage4_Caspian MC$Casp_mascon 9.e10 100.
if(`cat mascons_stage4_Caspian | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
  echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_Caspian | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
  exit
else
  cp mascons_stage4_Caspian mascons_stage4_tmp
endif

CoM100:
###################################################################
##                                                               ##
## reduce the cutoff RMS level down to 100. to improve pattern
##                                                               ##
###################################################################
setenv OMP_NUM_THREADS 5
cp mascons_stage4_tmp mascons_stage4_tmp
foreach region (Australasia Antarctica)
  ${version}/util/reshape_mascons mascons_stage4_tmp mascons_stage4_${region}_100 $region 9.e10 100. 1 Murra
  if(`cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
    echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
    exit
  else
    cp mascons_stage4_${region}_100 mascons_stage4_tmp
  endif
end

###################################################
# these run reasonably quickly but
# Eurasia takes 145 iterations and over 1 hour ...
setenv OMP_NUM_THREADS 10
foreach region ( Africa SAmerica NAmerica Eurasia)
  ${version}/util/reshape_mascons mascons_stage4_tmp mascons_stage4_${region}_100 $region 9.e10 100. 2 Amazo Casp
  if(`cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
    echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
    exit
  else
    cp mascons_stage4_${region}_100 mascons_stage4_tmp
  endif
end

# rerun the check on small mascons and CoM proximity
mv mascons_stage4_tmp mascons_stage4_RMS100
${version}/com/sh_cleanup_mascon_file -f mascons_stage4_RMS100
cp msc_file_tmp mascons_stage4_tmp


# output any remaining issues
$version/util/dist_flag mascons_stage4_tmp junk info > mascon.info.5
echo Mascon CoMs still too close together:
grep "Primary mascon" mascon.info.5
echo " "
echo "Mascons with too few ternarys      :" `grep -i few mascon.info.5`
echo " "
echo End of script





