#!/bin/csh -x


set land_area = 9.e10
set ocean_area = 9.e10
set ext = $3
set version = "~/gt"
set maxOMP = 10

# link the required files into the directory
ln -s -f  ~/gg/grace/tables/GEBCO14+Bedmap2_topo.nc .
ln -s -f  ~/gg/grace/tables/Und_min2.5x2.5_egm2008_isw=82_WGS84_TideFree_SE
ln -s -f  ~/gg/grace/tables/mascon.polygons .

#goto CoM100
#goto CPU1
goto skip_ocean

################################################################################################
# first, initialise the mascons
echo ${version}/util/init_mascons
${version}/util/init_mascons

# now, assign attributes to them (density, depth etc) and form 3x3 deg primary mascons
echo ${version}/util/classify_mascons
${version}/util/classify_mascons


# separate the continental from the ocean mascons. Assign a continental shelf depth of -0.1 m to remove it
${version}/util/separate_mascons mascons_stage2 mascons_stage3_0.1m -0.1
################################################################################################


#################################################################################################
# the oceans. Need to run the reshape of the oceans on compute2 in order to have enough memory. #
#################################################################################################
# reshape the arctic down to 3 deg tiles
# Arctic	: breaks 143 into 178 mascons in 193 iterations (15 mins)
setenv OMP_NUM_THREADS 5
${version}/util/reshape_mascons mascons_stage3_0.1m mascons_stage4_Arctic Arctic 9.e10 100.
set nterns = `cat mascons_stage4_Arctic | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l`
if($nterns  != 1485118)then
  echo We have lost some ternarys. There are only $nterns left ...
  exit
endif

# reshape the southern ocean down to 3 deg tiles
# Southern Ocean: breaks 172 into 208 mascons in XX iterations
${version}/util/reshape_mascons mascons_stage4_Arctic mascons_stage4_SthnO SthnO  9.e10  100.
set nterns = `cat mascons_stage4_SthnO | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l`
if($nterns  != 1485118)then
  echo We have lost some ternarys. There are only $nterns left ...
  exit
endif

# now the rest of the ocean. This one takes several hours ....
# Ocean		: breaks XX into XX mascons in XX iterations
setenv OMP_NUM_THREADS 8
${version}/util/reshape_mascons mascons_stage4_SthnO  mascons_stage4_ocean Ocean 9.e10   1000. 2 Arcti SthnO     
set nterns = `cat mascons_stage4_ocean | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l`
if($nterns  != 1485118)then
  echo We have lost some ternarys. There are only $nterns left ...
  exit
endif

# stop after doing the oceans and then transfer the rest to compute1
exit
################################################################################################



skip_ocean:
########################################################################################################
# now do all the others that can be done using multiple CPUs
# Africa	: breaks 269 into 333 mascons in 50 iterations
# SAmerica      : breaks 161 into 198 mascons in 64 iterations
# NAmerica      : breaks 202 into 244 mascons in 58 iterations
# Eurasia       : breaks 467 into 574 mascons in 72 iterations
cp mascons_stage4_ocean mascons_stage4_tmp
setenv OMP_NUM_THREADS 10
foreach region (Africa SAmerica NAmerica Eurasia)
  ${version}/util/reshape_mascons mascons_stage4_tmp mascons_stage4_${region} $region 9.e10 1000. 1 Casp  # exclude Casp for Europe (others will ignore it)
  if(`cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
    echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
    exit
  else
    cp mascons_stage4_${region} mascons_stage4_tmp
  endif
end

   
# Australia has 5 CPUs
# Australasia	: breaks 73 into 90 mascons in 45 iterations
setenv OMP_NUM_THREADS 5
foreach region (Australasia)
  ${version}/util/reshape_mascons mascons_stage4_tmp mascons_stage4_${region} $region 9.e10 1000. 1 Eyre  
  if(`cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
    echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
    exit
  else
    cp mascons_stage4_${region} mascons_stage4_tmp
  endif
end

CPU1:
# now the regions with 1 CPU. These all run really quickly.
setenv OMP_NUM_THREADS 1
foreach region (Japan Asian_isla Greenland)
  ${version}/util/reshape_mascons mascons_stage4_tmp mascons_stage4_${region} $region 9.e10 100.
  if(`cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
    echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
    exit
  else
    cp mascons_stage4_${region} mascons_stage4_tmp
  endif
end

# For now, just do Antarctica as a single shape (ie don't split off Thwaites/Pine Is etc)
# Antarctica	: breaks 106 into 136 mascons in 153 iterations
setenv OMP_NUM_THREADS 5
foreach region (Antarctica)
  ${version}/util/reshape_mascons mascons_stage4_tmp mascons_stage4_${region} $region 9.e10 1000.
  if(`cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
    echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
    exit
  else
    cp mascons_stage4_${region} mascons_stage4_tmp
  endif
end




# rename the final file
mv mascons_stage4_tmp mascons_stage4_190308

# finally, fix the small mascons and the CoM issues. The output file of the script is still called msc_file_tmp
# started at 9:39. Completed at ?????
/home/geod/pault/gt/com/sh_cleanup_mascon_file -f mascons_stage4_190308
cp msc_file_tmp mascons_stage4_190308_cleaned

###################################################################
##                                                               ##
## PT190308: extract out particular drainage basins              ##
##                                                               ##
###################################################################
setenv OMP_NUM_THREADS 1
cp mascons_stage4_190308_cleaned mascons_stage4_tmp
foreach region (Amazon MurrayDB)
  ${version}/util/grab_mascons mascons_stage4_tmp mascons_stage4_tmp2 drainage_basins $region Land 100.
  set last_mascon = `grep "  P" mascons_stage4_tmp2 | tail -1 | awk '{print $1}'`
  ${version}/util/reshape_mascons mascons_stage4_tmp2 mascons_stage4_$region MC$last_mascon 9.e10 100.
  ${version}/util/lost_ternarys mascons_stage4_$region
  if(`cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
    echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
    exit
  else
    cp mascons_stage4_${region} mascons_stage4_tmp
  endif
end

###################################################################
##                                                               ##
## PT190308: reshape the Caspian Sea into smaller mascons        ##
##                                                               ##
###################################################################
setenv OMP_NUM_THREADS 1
set Casp_mascon = `grep "  P" mascons_stage4_MurrayDB | grep PCasp | awk '{print $1}'`
${version}/util/reshape_mascons mascons_stage4_MurrayDB mascons_stage4_Caspian MC$Casp_mascon 9.e10 100.
if(`cat mascons_stage4_Caspian | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
  echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_Caspian | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
  exit
else
  cp mascons_stage4_Caspian mascons_stage4_tmp
endif

CoM100:
###################################################################
##                                                               ##
## reduce the cutoff RMS level down to 100. to improve pattern
##                                                               ##
###################################################################
setenv OMP_NUM_THREADS 5
cp mascons_stage4_tmp mascons_stage4_tmp
foreach region (Australasia Antarctica)
  ${version}/util/reshape_mascons mascons_stage4_tmp mascons_stage4_${region}_100 $region 9.e10 100. 1 Murra
  if(`cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
    echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
    exit
  else
    cp mascons_stage4_${region}_100 mascons_stage4_tmp
  endif
end

###################################################
# these run reasonably quickly but
# Eurasia takes 145 iterations and over 1 hour ...
setenv OMP_NUM_THREADS 10
foreach region ( Africa SAmerica NAmerica Eurasia)
  ${version}/util/reshape_mascons mascons_stage4_tmp mascons_stage4_${region}_100 $region 9.e10 100. 2 Amazo Casp
  if(`cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` != 1485118)then
    echo "Have lost one or more ternary mascons. There are only ", `cat mascons_stage4_$region | awk '{if (substr($0,8,3) == "  T") {print $1}}' | wc -l` "left. Stop processing"
    exit
  else
    cp mascons_stage4_${region}_100 mascons_stage4_tmp
  endif
end

# rerun the check on small mascons and CoM proximity
mv mascons_stage4_tmp mascons_stage4_RMS100
${version}/com/sh_cleanup_mascon_file -f mascons_stage4_RMS100
cp msc_file_tmp mascons_stage4_tmp


# output any remaining issues
$version/util/dist_flag mascons_stage4_tmp junk info > mascon.info.5
echo Mascon CoMs still too close together:
grep "Primary mascon" mascon.info.5
echo " "
echo "Mascons with too few ternarys      :" `grep -i few mascon.info.5`
echo " "
echo End of script





