#!/bin/csh -f

set version = ~/ga

if ($#argv == 0) then
  echo "sh_make_daily_AOD1B YYYY MM DD RLXX"
  exit
endif

set year = $1  
set month = $2
set day = $3
set RL_num = $4

# get the YYYY MM DD for the next day
#set next_day = `echo $day | awk '{printf "%2.2d", $1 + 1}'`
#set next_date = (`doy $year $month $next_day | head -1 | awk '{print substr($2,1,4), substr($2,6,2), substr($2,9,2)}'`) 
set next_date = `date --date="${year}-${month}-${day} next day" --rfc-3339='seconds' | awk '{print substr($0,1,4), substr($0,6,2), substr($0,9,2)}'`
set RL_short = `echo $RL_num | cut -c3-4`

# make the aod file
${version}/util/make_daily_AOD1B AOD1B_$year-${month}-${day}_X_${RL_short}.asc AOD1B_$next_date[1]-$next_date[2]-$next_date[3]_X_${RL_short}.asc aod_${year}-${month}-${day}.asc atm_tide_stokes.hs $RL_num

