#!/bin/csh -f

# script to plot the postfit correlations between a specific mascon and all others. The script will read an addnorm.vcv file
#
# P. Tregoning
# 27 September 2017

if ($#argv == 0)then
  echo "Runstring: sh_plot_mascon_correlation -msc 2391 -f addnorm.vcv -out addnorm_2391.correl -msc_crds_file mascons_stage4 -calc_correl Y/N"
  exit
endif


######### set defaults #####
set infile = addnorm.vcv
set msc = 2391
set outfile = ""
set msc_crds_file = "~/gg/grace/tables/mascons_stage4"
set calc_correl = "N"
set ymin = -1.05
set ymax = 1.05
set proj = "-JS0/-89.9/30/14"
set range = "-R0/360/-90/-60"
############################


##################### DECIPHER COMMAND LINE #######################
while ($#argv > 0 )
  set input = ( $argv )
  switch($input[1])
    case -f:
      set infile  = $input[2]
    breaksw
    case -msc:
      set msc  = $input[2]
    breaksw
    case -msc_crds_file:
      set msc_crds_file  = $input[2]
    breaksw
    case -calc_correl:
      set set calc_correl = "Y"
    breaksw
    case -out:
      set outfile  = $input[2]
    breaksw
    case -y:
      set ymin  = $input[2]
      set ymax  = $input[3]
    breaksw
    case -plot:
      set proj = "-JR"$input[3]"/10"
      set range = "-R"$input[3]/$input[5]/$input[2]/$input[4]
 endsw
  if ( $#argv > 0 ) shift argv
end
alldone:
######################################################################

if ($outfile == "")then
  set outfile = addnorm.correl
endif


# ok, so now we need to run the program to calculate the correlations
if($calc_correl == "Y")then
  echo ~/gt/util/calc_msc_correl $infile $outfile
  ~/gt/util/calc_msc_correl $infile $outfile
endif


########################################################################
plot:
# extract out the row of correlations for the requested mascon
echo "Extracting the correlations for mascon" $msc
set correlations = `head -$msc $outfile | tail -1 `
echo Extracted

# extract the lat/lon coordinates for each mascon
set lats = `cat $msc_crds_file | awk '{if (substr($0,8,3) == "  P") {print $5}}'`
set lons = `cat $msc_crds_file | awk '{if (substr($0,8,3) == "  P") {print $6}}'`
#set n_msc = `echo $correlations | wc -w`
set n_msc = `head -$msc $outfile | tail -1 | wc -w`

# make a file of the data
echo "Making file of lon/lat and correlation"
rm correl.dat ; touch correl.dat
set i = 1
while ($i <= $n_msc)
  echo $lons[$i] $lats[$i] $correlations[$i] >> correl.dat
  @ i = $i + 1
end

# now plot it spatially
gmt makecpt -Chaxby -T-0.525/0.525/0.05 > correl.cpt
## global
#set proj = "-JR30/18"
#set range = "-Rg"
set dot = 0.1
## India
#set proj = "-JM16"
#set range = "-R45/105/-15/40"
#set dot = 0.5
# Antarctic
#set proj = "-JS0/-89.9/30/14"
#set range = "-R0/360/-90/-60"
set dot = 0.2
gmt makecpt -Chaxby -T$ymin/$ymax/0.05 > correl.cpt

set psfile = correl_${msc}.ps
gmt psxy correl.dat $proj $range -X2 -Y10 -P -K -Sc$dot -Ccorrel.cpt -Ba10neSW > $psfile
gmt pscoast $proj $range -Wthin -O -K -A100000 >> $psfile
# plot a star at the mascon location
set lonlat = `grep " "$msc"  P" $msc_crds_file | awk '{print $6, $5}'`
echo Mascon location: $lonlat
gmt psxy $proj $range -O -K -Sa0.1 -G0 << end >> $outfile
$lonlat
end

gmt psscale -Ccorrel.cpt -D8/-2/15/0.5h -Ba0.1f0.05 -O >> $psfile

gs $psfile
















