#!/bin/csh -f

# Srinivas asked for a plot of the mascon uncertainties ....

set fit_file = $1
set msc_file = ~/gg/grace/tables/mascons_stage4_V003a

# get the primary mascon coordinates
grep "  P" $msc_file | awk '{if (substr($0,8,3) == "  P") {print $6, $5, $8 , sqrt($8*1.e-6), $11}}' > msc.lonlat

# get the solution uncertainties for the mascon parameters
grep " MC" $fit_file | awk '{print substr($0,79,12) * 1}' > tmp

# join them up
paste msc.lonlat tmp | awk '{printf "%10.4f %10.4f %20.10f %15.8f %15.8f\n", $1, $2, 1.e-10 * sqrt($5) * $3, $5, $3}' > msc_unc.dat

gmtinfo msc_unc.dat

plot:
set outfile = msc_unc.ps
set proj = "-JR-30/15"
set range = "-Rg"
makecpt -Chaxby -T0/20/.1 > msc_unc.cpt

psxy msc_unc.dat $proj $range -Ba1000:."$fit_file":nesw -X2 -Y19 -Sc0.1 -Cmsc_unc.cpt -P -K > $outfile
pscoast $proj $range -O -K -W1,grey -Dc -A10000 >> $outfile
psscale -D8/-0.5/15/0.5h -Cmsc_unc.cpt -Ba10:"postfit uncertainty (m)": -O -K >> $outfile

# build it again to plot sigma against area
paste msc.lonlat tmp | awk '{if ($5 > 1010.) {print $4, $6, $2, $1}}' > scatterplot_ocean.dat
paste msc.lonlat tmp | awk '{if ($5 < 1010.) {print $4, $6, $2, $1}}' > scatterplot_land.dat

echo scatterplot_ocean.dat: `gmtinfo scatterplot_ocean.dat`
set range = "-R10/1000/0.001/3000"
set proj = "-JX6l/11l"

makecpt -Chaxby -T-90/90/10 > scatter_lat.cpt

psxy scatterplot_land.dat -Ss0.1 -Cscatter_lat.cpt $proj $range -Ba100f50:"land length scale (km)":/200f100:"sigma (m)"::."Land":neSW -X+1 -Y-15 -O -K >> $outfile 
psxy scatterplot_ocean.dat  -Ss0.2 -Cscatter_lat.cpt  $proj $range -Ba1000f500:"ocean length scale (km)":/200f100:"sigma (m)"::."Ocean":nESw  -X+7 -O -K >> $outfile 
psscale -Cscatter_lat.cpt -D0/-1.7/15/0.5h -Ba20f10:"Latitude": -O -K >> $outfile


gs $outfile

