#!/bin/csh -f

if ($#argv == 0)then
  echo "sh_plot_inert -t YYYY MM DD -g1 GPS_A -g2 GPS_B -sca1 SCA_A -sca2 SCA_B [-plot_only N/Y ] "
  exit
endif

##################### SET DEFAULT VALUES    #######################
set gps1 = ""
set gps2 = ""
set sca1 = ""
set sca2 = ""
set plot_only = "Y"
######################################################################


##################### DECIPHER COMMAND LINE #######################
while ($#argv > 0 )
  set input = ( $argv )
  switch($input[1])
    case -t:
      set yr     = $input[2] ; shift argv
      set month  = $input[3] ; shift argv
      set day    = $input[4] ; shift argv
    breaksw
    case -gps1:
      set gps1  = $input[2]
    breaksw
    case -gps2:
      set gps2  = $input[2]
    breaksw
    case -sca1:
      set sca1  = $input[2]
    breaksw
    case -sca2:
      set sca2  = $input[2]
    breaksw
    case -plot_only:
      set plot_only  = $input[2]
    breaksw
 endsw
  if ( $#argv > 0 ) shift argv
end
alldone:
######################################################################

## set the file names if not entered
if($gps1 == "")then
  set gps1 = `echo $yr $month $day  | awk '{printf "GNV1B_%4.4d-%2.2d-%2.2d_A_02.asc\n",$1, $2, $3}'`
endif
if($gps2 == "")then
  set gps2 = `echo $yr $month $day  | awk '{printf "GNV1B_%4.4d-%2.2d-%2.2d_B_02.asc\n",$1, $2, $3}'`
endif
if($sca1 == "")then
  set sca1 = `echo $yr $month $day  | awk '{printf "SCA1B_%4.4d-%2.2d-%2.2d_A_02.asc\n",$1, $2, $3}'`
endif
if($sca2 == "")then
  set sca2 = `echo $yr $month $day  | awk '{printf "SCA1B_%4.4d-%2.2d-%2.2d_B_02.asc\n",$1, $2, $3}'`
endif

set outfile = `echo $yr $month $day | awk '{printf "inert_%4.4d_%2.2d_%2.2d.ps\n",$1, $2, $3}'`


if($plot_only == "N")then
  echo "Running: compare_inertial_frames  " $yr $month $day " $gps1 $gps2 $sca1 $sca2 > inert.out"
  ~/gt/util/compare_inertial_frames $yr $month $day $gps1 $gps2 $sca1 $sca2 > inert.out

  grep "perturbations" inert.out | grep -v NaN | awk '{print substr($0,30,78)}' > inert.dat
endif


goto plot_rpy


plot:
gmt psxy -JX15/7 -R1/3000/0/7 inert.dat -Ba500:"Epoch":/1:"AT angle (mrad)":.:"$yr $month $day":neSW -Wthin,255/0/0 -X3 -Y21 -P -K >$outfile

cat inert.dat | awk '{print $1, $3}' > tmp.dat
gmt psxy -JX15/7 -R1/3000/10/25 tmp.dat  -Ba500:"Epoch":/5:"CT angle (mrad)":neSW -Wthin,255/0/0 -Y-9.5 -O -K >> $outfile

cat inert.dat | awk '{print $1, $4}' > tmp.dat
gmt psxy -JX15/7 -R1/3000/10/25 tmp.dat  -Ba500:"Epoch":/5:"RAD angle (mrad)":neSW -Wthin,255/0/0 -Y-9.5 -O -K >> $outfile

gs $outfile
exit


plot_rpy:
echo "Plotting rpy differences in inertial frames  " $yr $month $day 
set miny = -7
set maxy = 7
set minx = 0
set maxx = 18000
grep "perturbations" inert.out | grep -v NaN | awk '{print substr($0,30,78)}' > inert.dat
cat inert.dat | awk '{print $1, $2}' > tmp.dat
gmt psxy -JX15/7 -R$minx/$maxx/$miny/$maxy tmp.dat -Ba2000f1000:"Epoch":/1:"Roll angle (mrad)":neSW -Wthin,255/0/0 -X3 -Y21 -P -K >$outfile

cat inert.dat | awk '{print $1, $3}' > tmp.dat
gmt psxy -JX15/7 -R$minx/$maxx/$miny/$maxy tmp.dat  -Ba2000f1000:"Epoch":/1:"Pitch angle (mrad)":neSW -Wthin,255/0/0 -Y-9.5 -O -K >> $outfile

cat inert.dat | awk '{print $1, $4}' > tmp.dat
gmt psxy -JX15/7 -R$minx/$maxx/$miny/$maxy tmp.dat  -Ba2000f1000:"Epoch":/1:"Yaw angle (mrad)":neSW -Wthin,255/0/0 -Y-9.5 -O -K >> $outfile

pstext -Y+19.5 -JX15/7 -R$minx/$maxx/$miny/$maxy -O -N << end >> $outfile
$minx $maxy  $yr $month $day
end

gs $outfile


