#!/bin/csh -f

# new script to do various things to the ACC1B data, then call a python script to enable interactive plotting of the values
#
# P. Tregoning
# 6 August 2018

if ($#argv == 0 ) then
  echo "sh_plot_ACC_v4 -t YYYY MM DD -sat A/B/C/D"
  exit
endif

##################### DEFAULT VALUES #######################
set sat = (A)
set mission = 0
set version = ~/gt
set directory = "./"
############################################################


##################### DECIPHER COMMAND LINE #######################
while ($#argv > 0 )
  set input = ( $argv )
  switch($input[1])
    case -version:
      set version = $input[2] ; shift argv
    breaksw
    case -t:
      set yr     = $input[2] ; shift argv
      set month  = $input[3] ; shift argv
      set day    = $input[4] ; shift argv
    breaksw
    case -mission:
      set mission = $input[2] ; shift argv
    breaksw
    case -sat:
      set sat = $input[2] ; shift argv
    breaksw
 endsw
  if ( $#argv > 0 ) shift argv
end
alldone:
######################################################################

# print out what is going to happen
echo "Plot four temperatures from AHK data for day " $yr $month $day "for satellites " GRACE $sat  


# create the AHK1B file name, depending on date and mission
if ($mission == 0)then
  set RL_num = 02
  set ahk1b_file1 = ${directory}AHK1B_${yr}-${month}-${day}_${sat}_${RL_num}.asc
  $version/com/sh_extract_level1B $yr $month $day AHK RL$RL_num
else if ($mission == 1) then
  set RL_num = 00
  set ahk1b_file1 = ${directory}AHK1B_${yr}-${month}-${day}_${sats}_${RL_num}.txt
endif


# now, extract out the temperatures for the sensor unit (SU), internal core, iterface control unit (ICU) power supply board, and ICE A/D converter. These are the ones used by Klinger and Flury (2016)
grep "00000111111111111111111111000000" $ahk1b_file1 | awk '{print $1, $15, $16, $17, $21}' > AHK1b_${sat}.dat


# now call the python script to plot the data
python ${version}/com/plot_AHK_temps.py AHK1b_${sat}.dat

exit






