#!/bin/csh -f

# script to plot the following figures related to a single tempered iteration:
#   1. the apriori that went into it
#   2. the estimate
#   3. the difference from the previous iteration estimate
#   4. the apriori created from it
#
# P. Tregoning
# 1 December 2022

if ($#argv == 0)then
  echo "sh_plot_tiX YYYY MM iteration iter_version mascons_stage5_V006_200km plot_only [Y/N] "
  exit
endif

set year = $1
set month = $2
set iter = $3
set previous_iter = `echo $iter | awk '{print $1 - 1}'`
set iter_version_apr = $4
set iter_version_msc = $5
set mascon_file = $6
set plot_only = $7

set version = ~/ga

set msc_dir = "../../addnorm"
set apr_dir = "../$year"

if ($plot_only == "Y")goto plot


# create the msc_to_plot file of the apriori of the previous iteration
echo " "
echo "****A priori file for iteration " $iter ":" ${apr_dir}/aprA_${year}-${month}_ti${previous_iter}${iter_version_apr}.vcv
${version}/util/colour_mascons -tp -90 0 90 360 $mascon_file ${apr_dir}/aprA_${year}-${month}_ti${previous_iter}${iter_version_apr}.vcv VCV N N 10
mv msc_to_plot.dat msc_to_plot_aprA_ti${previous_iter}.dat


# create the plot file of the estimate for this iteration
echo " "
echo "****Estimate for iteration " $iter ":" ${msc_dir}/mscA_${year}-${month}_8ti${iter}${iter_version_msc}.vcv
${version}/util/colour_mascons -tp -90 0 90 360 $mascon_file ${msc_dir}/mscA_${year}-${month}_8ti${iter}${iter_version_msc}.vcv VCV N N 10
mv msc_to_plot.dat msc_to_plot_mscA_ti${iter}.dat

# create difference between estimate for this and previous iterations
echo " "
echo "****Difference between " ${msc_dir}/mscA_${year}-${month}_8ti${iter}${iter_version_msc}.vcv and ${msc_dir}/mscA_${year}-${month}_8ti${previous_iter}${iter_version_msc}.vcv
${version}/util/diff_ternarys $mascon_file  ${msc_dir}/mscA_${year}-${month}_8ti${iter}${iter_version_msc}.vcv $mascon_file  ${msc_dir}/mscA_${year}-${month}_8ti${previous_iter}${iter_version_msc}.vcv msc_to_plot_ti${iter}-ti${previous_iter}.dat N N 10 1.0

goto skip_apriori2
# create the plot file for the apriori from this iteration. 
echo " "
echo "****A priori file from iteration " $iter ":" ${apr_dir}/aprA_${year}-${month}_ti${iter}${iter_version_apr}.vcv
${version}/util/colour_mascons -tp -90 0 90 360 $mascon_file ${apr_dir}/aprA_${year}-${month}_ti${iter}${iter_version_apr}.vcv VCV N N 10
mv msc_to_plot.dat msc_to_plot_aprA_ti${iter}.dat
skip_apriori2:


plot:

# try making the page something other than a4
set outfile = plot_${year}-${month}_ti${iter}${iter_version_apr}.ps

gmt gmtset PS_MEDIA ledger
gmt gmtset FONT_TITLE 15p,Helvetica,black
gmt makecpt -Cgrace -T-900/900/10 > ewh.cpt
gmt makecpt -Cgrace_lopsided5 -T-10000/2000/100 > ewh_polar.cpt

set proj = "-JR30/13"
set proj_ant = "-JS0/-89.9/30/6.5"
set proj_arctic = "-JS0/89.9/45/6.5"

set range = "-Rg"
set range_ant = "-R0/360/-90/-60"
set range_arctic = "-R0/360/55/90"

#######################################
# plot the apriori for this iteration
echo Plotting apriori for tempered iteration $iter
gmt psxy msc_to_plot_aprA_ti${previous_iter}.dat $proj $range -: -Sc0.2 -Cewh.cpt -X0.3 -Y17 -P -K > $outfile
gmt pscoast $proj $range -Ba1000:."aprA_${year}-${month}_ti${previous_iter}${iter_version_apr}":nesw -Dc -Wthin,100/100/100 -O -K >> $outfile
gmt psscale -Cewh.cpt -D6.5/-1/12/0.3h -Ba300f150:"EWH (mm)": -O -K >> $outfile

gmt psxy msc_to_plot_aprA_ti${previous_iter}.dat $proj_ant $range_ant -: -Sc0.2 -Cewh.cpt -Y-10 -O -K >> $outfile
gmt pscoast $proj_ant $range_ant -Ba1000nesw -Dc -Wthin,100/100/100 -O -K >> $outfile
gmt psscale -Cewh_polar.cpt -D6.5/-1/12/0.3h -Ba2000f1000:"EWH (mm)": -O -K >> $outfile


gmt psxy msc_to_plot_aprA_ti${previous_iter}.dat $proj_arctic $range_arctic -: -Sc0.2 -Cewh.cpt -X+7 -O -K >> $outfile
gmt pscoast $proj_arctic $range_arctic -Ba1000nesw -Dc -Wthin,100/100/100 -O -K >> $outfile


#######################################
# plot the estimate for this iteration
echo Plotting estimate for tempered iteration $iter
gmt psxy msc_to_plot_mscA_ti${iter}.dat $proj $range -: -Sc0.2 -Cewh.cpt -X+7.5 -Y+10 -O -K  >> $outfile
gmt pscoast $proj $range -Ba1000:."mscA_${year}-${month}_ti${iter}${iter_version_apr}":nesw -Dc -Wthin,100/100/100 -O -K >> $outfile
gmt psscale -Cewh.cpt -D6.5/-1/12/0.3h -Ba300f150:"EWH (mm)": -O -K >> $outfile

gmt psxy msc_to_plot_mscA_ti${iter}.dat $proj_ant $range_ant -: -Sc0.2 -Cewh.cpt -Y-10 -O -K >> $outfile
gmt pscoast $proj_ant $range_ant -Ba1000nesw -Dc -Wthin,100/100/100 -O -K >> $outfile
gmt psscale -Cewh_polar.cpt -D6.5/-1/12/0.3h -Ba2000f1000:"EWH (mm)": -O -K >> $outfile


gmt psxy msc_to_plot_mscA_ti${iter}.dat $proj_arctic $range_arctic -: -Sc0.2 -Cewh.cpt -X+7 -O -K >> $outfile
gmt pscoast $proj_arctic $range_arctic -Ba1000nesw -Dc -Wthin,100/100/100 -O -K >> $outfile


#######################################
# plot the adjustment from the previous iteration
echo Plotting   ti$iter - ti$previous_iter
gmt psxy msc_to_plot_ti${iter}-ti${previous_iter}.dat $proj $range -: -Sc0.2 -Cewh.cpt -X+7.5 -Y+10 -O -K  >> $outfile
gmt pscoast $proj $range -Ba1000:."mscA_ti${iter}-mscA_ti${previous_iter}":nesw -Dc -Wthin,100/100/100 -O -K >> $outfile
gmt psscale -Cewh.cpt -D6.5/-1/12/0.3h -Ba300f150:"EWH (mm)": -O -K >> $outfile

gmt psxy msc_to_plot_ti${iter}-ti${previous_iter}.dat $proj_ant $range_ant -: -Sc0.2 -Cewh.cpt -Y-10 -O -K >> $outfile
gmt pscoast $proj_ant $range_ant -Ba1000nesw -Dc -Wthin,100/100/100 -O -K >> $outfile
gmt psscale -Cewh_polar.cpt -D6.5/-1/12/0.3h -Ba2000f1000:"EWH (mm)": -O -K >> $outfile


gmt psxy msc_to_plot_ti${iter}-ti${previous_iter}.dat $proj_arctic $range_arctic -: -Sc0.2 -Cewh.cpt -X+7 -O -K >> $outfile
gmt pscoast $proj_arctic $range_arctic -Ba1000nesw -Dc -Wthin,100/100/100 -O  >> $outfile


gs $outfile








