#!/bin/csh -f

# script to plot the RMS of the difference of two solutions, computed on latitude bands of ternary mascons. It uses
# diff_ternarys to calculate the differences between the solutions, then groups them into ternary latitude bands, then
# plots RMS as a function of latitude
#
# P. Tregoning
# 2 March 2020

if($#argv == 0)then
  echo "sh_RMS_by_latitude soln1 mascons_soln1 soln2 mascons_soln2"
  echo "e.g. sh_RMS_by_latitude   stage5_t5.vcv mascons_stage5 GSFC_apriori_2016_07_stage5.vcv mascons_stage4"
  exit
endif

gmt gmtset FONT_TITLE 15

set version = ~/gt
set soln1 = $1
set msc1 = $2
set soln2 = $3
set msc2 = $4
set mscdiff = ${soln1}_${soln2}_mscdiff.dat
if($#argv == 5)goto plot


#goto plot

 
# difference them and output on ternary mascons
if($soln1 != $soln2) then
  $version/util/diff_ternarys $msc1 $soln1 $msc2 $soln2 $mscdiff
else
  $version/util/colour_mascons -tp -90 0 90 360 $msc1 $soln1 VCV N
  mv msc_to_plot.dat $mscdiff
endif


# now, make a list of all ternary latitudes
set tern_lats = `grep " 360.0000" $mscdiff | awk '{print $1}'`
set nlats = `grep " 360.0000" $mscdiff | awk '{print $1}' | wc -w`
echo nlats = $nlats

# loop through all the ternary latitudes and extract out all the ternarys
#set nlats = `echo $tern_lats[1-540] | wc -w`
#set nlats = 1079

echo RMS values of difference between files $soln1 and $soln2 >! RMS_${soln1}_${soln2}.dat
set i = 1
while ($i <= $nlats)
  cat $mscdiff | awk '{if ($1 == '$tern_lats[$i]') {print $3, sqrt($6*$6 + $7*$7), '$tern_lats[$i]'}}' > tmp.dat
  set wrms = `~pault/bin/WRMS tmp.dat | awk '{print $3}'` 
  echo $tern_lats[$i] $wrms | awk '{printf "%10.4f  %10.2f\n", $1, $2}'
  echo $tern_lats[$i] $wrms | awk '{printf "%10.4f  %10.2f\n", $1, $2}' >> RMS_${soln1}_${soln2}.dat

  @ i = $i + 1
end


# derive information to plot uncertainty as a function of latitude
set lats = `cat $msc1 | awk '{if (substr($0,8,3) == "  P") {print $5}}'`
set EWH_unc = `grep " MC" $soln1 | awk '{print $6 * 1.e3}'`
set nlats = `cat $msc1 | awk '{if (substr($0,8,3) == "  P") {print $5}}' | wc -w`

set i = 1
echo Uncertainty of primary mascons of $soln1 as a function of latitude >! unc.dat
while ($i <= $nlats)
 echo $lats[$i] $EWH_unc[$i] >> unc.dat
 @ i = $i + 1
end


# now plot it
plot:
set outfile = lat_RMS.ps
set range = "-R-90/90/0/10"
set proj = "-JX15/10"

# RMS as a function of latitude
gmt psxy -h1 RMS_${soln1}_${soln2}.dat $proj $range -Ba30f10:"Latitude":/4f2:"RMS (mm)"::."RMS of $soln1 - $soln2":neSW -W2,red -X2 -Y17 -P -K > $outfile
gmt psxy -h1 RMS_${soln1}_${soln2}.dat $proj $range -Sc0.1 -Gred -O -K >> $outfile
 # PT200307: hardwire the plotting of a second solution RMS
 gmt psxy -h1 RMS_addnorm_mar7_noCoM.vcv_GSFC_apriori_2016_07_stage5.vcv.dat $proj $range -W2,lightblue  -O -K >> $outfile
 #gmt psxy -h1 RMS_addnorm_mar7_noCoM.vcv_GSFC_apriori_2016_07_stage5.vcv.dat $proj $range -Sc0.1 -Glightblue -O -K >> $outfile

# uncertainty of primary mascons as a function of latitude
set range = "-R-90/90/0/70"
gmt psxy -h1 unc.dat -Sc0.1 -Gblue $proj $range -Ba30f10:"Latitude":/10f5:"Uncertainty (mm)"::."Primary mascon uncertainty of $soln1 ":neSW -O -K -Y-14 >> $outfile


gs $outfile




