#!/bin/bash
#
# change version from ~/gt to ~/ga in grace com scripts
#   - use after promoting test code to active
#   - move revised scripts from /tmp/newsh to ~/ga/com when checked
#  HM_190712

D1=/tmp/d1$$
D2=/tmp/newsh
mkdir $D1
mkdir $D2
rm ${D2}/*
pwd

for F in `ls sh*`
do
  cat $F|sed s:'= ~/gt':'= ~/ga': \
        |sed s:'=~/gt':'= ~/ga':  \
        |sed s:'"~/gt"':'"~/ga"': \
        |sed s:' ~/gt/':' ~/ga/': \
	 >${D1}/$F
	   
  C=`diff -q $F ${D1}/$F`
  if [ "$C" ]
  then
    mv ${D1}/$F ${D2}/$F
  fi
done


for F in `ls $D2`
do
  diff $F ${D2}/$F
done

rm $D1
N=`ls ${D2} |wc -l`
echo $N files changed

