#!/bin/csh -f

# script to rerun the GRACE-FO solutions using the ACH hybrid transplant data for GF2
#
# P. Tregoning
# 25 October 2022

if ($#argv == 0)then
  echo sh_rerun_ACH YYYY MM DD ~/ga/tables/mascons_stage5_V006_200km  ~/ga/tables/apriori_annuals_b8z_200km_1yr.txt
  exit
endif

set year = $1
set month = $2
set day = $3
set mascon_file = $4
set apriori_model_file = $5

set version = ~/ga
set two_iter3 = N

#################################################################
##              measurement uncertainties
#################################################################
set pos_unc = 0.07        
# 70 um/s  uncertainty on all GNV1B velocities
set vel_unc = 0.07e-3     
# 0.3 um/s uncertainty on all KBR1B range rate observations
set kbrr_unc_iter0 = 1.e0
set kbrr_unc = 0.8e-6     
set kbrr_unc_iter3 = 10.e-6
# 1.0 nm/s^2 uncertainty on all KBR1B range acceleration observations
set kbra_unc_iter0 = 1.e0
set kbra_unc = 1.e-9     

#################################################################
##              set up the day
#################################################################

# default mascon file
set mascon_file = "mascons_stage5_V006_200km"
ln -sf $version/tables/$mascon_file .
ln -sf $version/tables/$mascon_file'.flag' .

# apriori model for the mascons
set msc_model_file = $version/tables/apriori_annuals_b8z_200km_1yr.txt
ln -sf $msc_model_file .

# mascon regularisation file
set mascon_reg_file = "mascons_V006_200km_I100.reg "
ln -sf $version/tables/$mascon_reg_file .

# type of GTORB file
set gtorb_type = "h5"

# PT180622: which mission ? 0: GRACE, 1: GRACE FO, 2: GRACE II
set mission = 1
set RL_num = 04

# model to linearise the accelerometer data
# PT220429: use "therm" for GRACE, "none" for GRACE-FO
if ($mission == 0)then
  set acc_model_AT = therm
else if ($mission == 1)then
  set acc_model_AT = therm
endif

# model to linearise the accelerometer data
# PT220429: use "therm" for GRACE, "none" for GRACE-FO
set acc_model_AT = none
# always use the fft model on cross-track, to remove long-period thermal signal
set acc_model_CT = fft
# we have no model for thermal effects in the radial component
set acc_model_RD = none

# satellite information
set setup_cmdfile = "GRACE_FO.input"
set gracefit_cmdfile = "gracefit.cmd.template_GRACEFO"
set sat1 = "C"
set sat2 = "D"

# set up the input files for GRACEORB for a 24-hr iter3 integration
${version}/com/sh_setup_day_soln -t $year $month $day 00 00 00 86340 -mission $mission -type $gtorb_type -acc_model $acc_model_AT $acc_model_CT $acc_model_RD -mascon_file $mascon_file -extend 21600 -mascon_surface topography -msc_apriori_model $msc_model_file -version $version -use_ACH Y


# there is no GRACE_FO_IC.dat file in ga/tables!!!! for 2022 processing, link to just that one
ln -sf ~/ga/tables/GRACE_FO_IC_2022.dat GRACE_FO_IC.dat

# set up the parameters for the processing of iter3
cp ../${year}-${month}-${day}/"IC_"${year}"_"${month}"_"${day}"_iter2.vcv" .
cp ${setup_cmdfile} ${setup_cmdfile}_ACH.iter3 
sed -i 's/APRIORI_FILE      :.*/APRIORI_FILE      : IC_'"${year}"'_'"${month}"'_'"${day}"'_iter2.vcv/'  ${setup_cmdfile}_ACH.iter3
sed -i 's/USE_APRIORI_ICS   : 0/USE_APRIORI_ICS   : 15/'  ${setup_cmdfile}_ACH.iter3 
sed -i 's/MASCON            : N/MASCON            : Y/'  ${setup_cmdfile}_ACH.iter3
sed -i 's/USE_APRIORI_MCS   : N/USE_APRIORI_MCS   : Y/'  ${setup_cmdfile}_ACH.iter3
sed -i 's/MSC_APRIORI_FILE  : none/MSC_APRIORI_FILE  : msc_apriori_'"${year}"'_'"${month}"'.vcv/'  ${setup_cmdfile}_ACH.iter3

#################################################################
##              process the day
#################################################################

# GRACEORB
setenv OMP_NUM_THREADS 10
~/ga/graceorb/graceorb ${setup_cmdfile}_ACH.iter3 in_file_C_${year}-${month}-${day}_00 &
~/ga/graceorb/graceorb ${setup_cmdfile}_ACH.iter3 in_file_D_${year}-${month}-${day}_00 &
wait

# rename the orbits
mv GTORB_${year}-${month}-${day}_00-00-00_${sat1}_${RL_num}.$gtorb_type  GTORB_${year}-${month}-${day}_00-00-00_${sat1}_${RL_num}_IC_ACH_iter3.$gtorb_type
mv GTORB_${year}-${month}-${day}_00-00-00_${sat2}_${RL_num}.$gtorb_type  GTORB_${year}-${month}-${day}_00-00-00_${sat2}_${RL_num}_IC_ACH_iter3.$gtorb_type


# GRACEFIT
iter3_gracefit:
# PT190725: switch on the cosine fft filter on the kbrr and kbra. Low- and high-frequency cutoffs defined by Bec McGirr from various tests.
cp ${version}/templates/${gracefit_cmdfile} gracefit_msc_iter3.cmd
sed -i 's/shadow:   0/shadow:   1/'  gracefit_msc_iter3.cmd
sed -i 's/ mission: M/ mission: '"$mission"'/' gracefit_msc_iter3.cmd
sed -i 's/PPP/'"$pos_unc"'/g' gracefit_msc_iter3.cmd
sed -i 's/VVV/'"$vel_unc"'/g' gracefit_msc_iter3.cmd
sed -i 's/KBRR_SIG/'"$kbrr_unc_iter3"'/' gracefit_msc_iter3.cmd
sed -i 's/KBRA_SIG/'"$kbra_unc"'/' gracefit_msc_iter3.cmd
sed -i 's/SCLX/1.0/' gracefit_msc_iter3.cmd
sed -i 's/SCLY/1.0/' gracefit_msc_iter3.cmd
sed -i 's/SCLZ/1.0/' gracefit_msc_iter3.cmd
sed -i 's/ kb_cos_fft: 0 / kb_cos_fft: 1 /' gracefit_msc_iter3.cmd
sed -i 's/kb_NR: 0 0/kb_NR: 0 1/' gracefit_msc_iter3.cmd
sed -i 's/mascons:            0/mascons:            1/' gracefit_msc_iter3.cmd
sed -i 's/msc_len_const:      0/msc_len_const:      1/' gracefit_msc_iter3.cmd



setenv OMP_NUM_THREADS 10
rm GRACEFIT.fatal >& /dev/null
# PT220126: run either a full 24hr solution or a 00-12hr then 12-24hr
if ($two_iter3 == "N")then
  ${version}/gracefit/gracefit gracefit_msc_iter3.cmd msc_${year}_${month}_${day}_ACH_iter3.rms 4 GTORB_${year}-${month}-${day}_00-00-00_${sat1}_${RL_num}_IC_ACH_iter3.$gtorb_type GTORB_${year}-${month}-${day}_00-00-00_${sat2}_${RL_num}_IC_ACH_iter3.$gtorb_type $year $month $day $mascon_reg_file 0 0 0 0 0 0 0 0 0 0 0 0
else if ($two_iter3 == "Y")then
  # invert the first 12 hours of data
  cat gracefit_msc_iter3.cmd | sed s/"end_neq:  "/"end_neq: 8640"/ > gracefit_msc_iter3_00-12hr.cmd
  ${version}/gracefit/gracefit gracefit_msc_iter3_00-12hr.cmd msc_${year}_${month}_${day}_iter3_ACH_00_12hr.rms 4 GTORB_${year}-${month}-${day}_00-00-00_${sat1}_${RL_num}_IC_iter3.$gtorb_type GTORB_${year}-${month}-${day}_00-00-00_${sat2}_${RL_num}_IC_iter3.$gtorb_type $year $month $day $mascon_reg_file 0 0 0 0 0 0 0 0 0 0 0 0

  # invert the latter 12 hours of data
  cat gracefit_msc_iter3.cmd | sed s/"start_neq:  1"/"start_neq:  8640"/ > gracefit_msc_iter3_12-24hr.cmd
  ${version}/gracefit/gracefit gracefit_msc_iter3_12-24hr.cmd msc_${year}_${month}_${day}_iter3_ACH_12_24hr.rms 4 GTORB_${year}-${month}-${day}_00-00-00_${sat1}_${RL_num}_IC_iter3.$gtorb_type GTORB_${year}-${month}-${day}_00-00-00_${sat2}_${RL_num}_IC_iter3.$gtorb_type $year $month $day $mascon_reg_file 0 0 0 0 0 0 0 0 0 0 0 0
endif



