#!/bin/csh -f

echo "sh_which_mascon lat lon [~/gg/grace/tables/mascons_stage4_V002 ]"

set lat = $1
set lon = $2
if ($#argv == 3)then
  set msc_file = $3
else
  set msc_file = ~/gg/grace/tables/mascons_stage4_V002
endif

~/ga/util/which_mascon $lat $lon > tmp.out
tail -1 tmp.out
set msc_tern = `tail -1 tmp.out | awk '{print $8}'`

# get the primary mascon number
grep $msc_tern $msc_file | awk '{if ($1 == '$msc_tern') {print $0}}'
set msc_prim = `grep $msc_tern $msc_file | awk '{if ($1 == '$msc_tern'  && substr($0,8,3) == "  T") {print $10}}' `
grep $msc_prim $msc_file | awk '{if ($1 == '$msc_prim' && substr($0,8,3) == "  P") {print $0}}' 
echo " "
echo Ternary: $msc_tern .... Primary: $msc_prim
\rm tmp.out
