#!/bin/csh -f

# convert YMD to decimal year using the generic "date" command
#
# P. Tregoning
# 28 February 2022

if ($#argv == 0) then
  echo sh_ymd_to_decyear YYYY MM DD
  exit
endif

set year = $1
set mm   = $2
set dd   = $3

set doy = `date -d ${year}-${mm}-${dd} +%j`

# days in this year
set days_in_year = `date -d ${year}-12-31 +%j`

set decyear = `echo $year $doy $days_in_year | awk '{printf "%10.5f\n", $1 + $2 / $3}'`

echo $decyear
